---
env          :
  browser: true
  jest   : true
  es2020 : true
parser : '@typescript-eslint/parser' #Specifies the ESLint parser
plugins:
  - '@typescript-eslint'
#   - 'prettier' #commented as we don't want to run performance hog prettier through eslint as it's slow
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended' #Uses the recommended rules from the @typescript-eslint/eslint-plugin
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:prettier/recommended' #Enables eslint-plugin-prettier and displays prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.
parserOptions:
  project     :
    - './tsconfig.json'
#     - './cypress/tsconfig.json'
  #tsconfigRootDir: __dirname
  #  //ecmaVersion  : 2017, // Allows for the parsing of modern ECMAScript features. Already set in env above ^
  sourceType  : 'module' # Allows for the use of imports
  ecmaFeatures:
    jsx: true #Allows for the parsing of JSX.
rules   :
  #Place to specify ESLint rules. Can be used to overwrite rules specified from the extended configs
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-unused-vars"               : warn
  "@typescript-eslint/no-explicit-any"              : off
  "@typescript-eslint/no-empty-function"            : off
  quotes                     : [warn, double]
  "@typescript-eslint/quotes": [warn, double]
  prettier/prettier:
    - warn
    - printWidth        : 100
      trailingComma     : "es5"
      jsxBracketSameLine: true
